### PR TITLE
fix: remove suffix

### PR DESCRIPTION
**Pull request by juanpicado**
add new test scenarios

### CODE REVIEW

**Comment by DanielRuf** [comment]
Might be better to update the lockfile in a separate commit. This would make the diffs much smaller and better to review locally =)

**Comment by anikethsaha** [comment]
yeah true, but when we make changes related to dep like version changing or dep remove/add,  isn't it required to use the committed lock file in order to build the same env?

Having it in separate commit is useful cause it makes things kind opt-in or optional

**Comment by DanielRuf** [comment]
> yeah true, but when we make changes related to dep like version changing or dep remove/add, isn't it required to use the committed lock file in order to build the same env?

Make two commits and push after these two.

**Comment by DanielRuf** [comment]
Only the pushes trigger CI, also see how we did it at https://github.com/bitExpert/mattermost-client-node/commits/develop

This also makes smaller commit objects / blobs in most cases and better compression in Git itself.

**Comment by anikethsaha** [comment]
> Make two commits and push after these two.

lock file commit should be the last one?

**Comment by DanielRuf** [comment]
> lock file commit should be the last one?

Exactly.

**Comment by anikethsaha** [comment]
> > lock file commit should be the last one?
> 
> Exactly.

yea...make sense 👍

**Pull request merged**
