### PR TITLE
feat: added Typescript templates

### PR DESCRIPTION
**Pull request by anikethsaha**
Added typescript templates and default template is typescript.

@juanpicado I would like to know if you have anything planned for v1 apart from this

### CODE REVIEW

**Comment by juanpicado** [comment]
working on it ....

in the meantime 

- [ ] add yourself as additional author to readme
- [ ] we need automate releases (I can give you some permissions in this repo to achieve that)

**Comment by anikethsaha** [comment]
> the gulp config is wrong,

Working on the gulp config, Actually, I am new to gulp eco but still loving it. I guess I can make the config work.
I will submit a new PR to fix it. then I will rebase this one 👍 

> The verdaccio types are missing

Can you mention which ones?

**Comment by juanpicado** [comment]
I merged the other ticket, I think we can update this one or just merge?

**Comment by anikethsaha** [comment]
I will rebase this along with the gulp src pattern change. 

Also @juanpicado i didnt get this one

> in the meantime
 add yourself as additional author to readme

**Comment by anikethsaha** [comment]
rebase and gulp pattern done 👍

**Comment by anikethsaha** [comment]
cc @juanpicado

**Pull request merged**
